import { readFileSync } from 'fs';
import { resolve } from 'path';
import { type Plugin } from 'vite';

/**
 * Inlines the camera-data content hash into index.html as window.__DATA_VERSION__
 * so the runtime meta.json fetch can append a ?v=<hash> cache-busting param.
 *
 * build-db.py writes public/data/version.txt (an 8-char sha256 of meta.json),
 * so the hash - and therefore the fetched URL - only changes when the camera
 * data actually changes, not on every unrelated build.
 */
export function inlineDataVersion(): Plugin {
  return {
    name: 'inline-data-version',
    transformIndexHtml(_, ctx) {
      const root = ctx.server?.config.root ?? process.cwd();
      const versionPath = resolve(root, 'public/data/version.txt');
      let version = '';
      try {
        version = readFileSync(versionPath, 'utf8').trim();
      } catch {
        // version.txt is generated by build-db.py; before the first build (or in
        // a source-only checkout) it may be absent - fall back to no param.
        version = '';
      }
      return [
        {
          tag: 'script',
          children: `window.__DATA_VERSION__=${JSON.stringify(version)};`,
          injectTo: 'head',
        },
      ];
    },
  };
}
