/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViewRouteImport } from './routes/view'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewStateIdRouteImport } from './routes/view.$stateId'

const ViewRoute = ViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewStateIdRoute = ViewStateIdRouteImport.update({
  id: '/$stateId',
  path: '/$stateId',
  getParentRoute: () => ViewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/view': typeof ViewRouteWithChildren
  '/view/$stateId': typeof ViewStateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/view': typeof ViewRouteWithChildren
  '/view/$stateId': typeof ViewStateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/view': typeof ViewRouteWithChildren
  '/view/$stateId': typeof ViewStateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/view' | '/view/$stateId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/view' | '/view/$stateId'
  id: '__root__' | '/' | '/view' | '/view/$stateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewRoute: typeof ViewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/view': {
      id: '/view'
      path: '/view'
      fullPath: '/view'
      preLoaderRoute: typeof ViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$stateId': {
      id: '/view/$stateId'
      path: '/$stateId'
      fullPath: '/view/$stateId'
      preLoaderRoute: typeof ViewStateIdRouteImport
      parentRoute: typeof ViewRoute
    }
  }
}

interface ViewRouteChildren {
  ViewStateIdRoute: typeof ViewStateIdRoute
}

const ViewRouteChildren: ViewRouteChildren = {
  ViewStateIdRoute: ViewStateIdRoute,
}

const ViewRouteWithChildren = ViewRoute._addFileChildren(ViewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewRoute: ViewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
